# Prime Factors Generated by CoPilot

#-------------------------------------------------------------------------------
# Formal Specifications:
#-------------------------------------------------------------------------------
# requires val is an integer
# returns list of prime factors of val

#-------------------------------------------------------------------------------
# Copilot Code: (starts)
#-------------------------------------------------------------------------------

def primeFactors(val: int) -> list:
    factors = []
    while val % 2 == 0:
        factors.append(2)
        val = val // 2
    for i in range(3, int(val ** 0.5) + 1, 2):
        while val % i == 0:
            factors.append(i)
            val = val // i
    if val > 2:
        factors.append(val)
    return factors

#-------------------------------------------------------------------------------
# Copilot Code: (ends)
#-------------------------------------------------------------------------------
