# Binary Search Generated by CoPilot
# reference: https://ece.uwaterloo.ca/~agurfink/stqam/rise4fun-Dafny/
#-------------------------------------------------------------------------------
# Formal Specifications:
#-------------------------------------------------------------------------------
# requires a sorted array
# requires each input array to have only unique elements
# ensures a -1 return value if target is not in the array
# ensures the index of the target is returned if the target exists in the array


#-------------------------------------------------------------------------------
# Copilot Code: (starts)
#-------------------------------------------------------------------------------

def binary_search(arr: list, target: int) -> int:
    low = 0
    high = len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1
#-------------------------------------------------------------------------------
# Copilot Code: (ends)
#-------------------------------------------------------------------------------

if __name__ == "__main__":
    arr = [1,2,3,4,5,6,7,8,9]
    target = 4
    print(binary_search(arr, target))
    print(len(arr))